### ISSUE TITLE
Three missed apps not fixed by StartupWMClassFixer

### ISSUE THREAD

**Issue by gusbemacbe** [bilelmoussaoui/StartupWMClassFixer#24]
Hi @bilelmoussaoui !

Check the last comment: https://forum.manjaro.org/t/solved-kde-tray-icons-blurry-for-installed-applications/63010/8?u=gusbemacbe

The three apps - Barrier, Remmina, and Slack are not listed in the database.csv. 

## Update

Also add Google Chromium (different of Google Chrome) and Hangouts

**Comment by bilelmoussaoui** [comment]
Could you send a PR to fix those please? Thanks

**Comment by bilelmoussaoui** [comment]
By checking the forum link, I think the solution is to use Hardcode-Tray instead.

**Comment by gusbemacbe** [comment]
May I list them in your repository Hardcode-Tray? And in this repository?

**Comment by bilelmoussaoui** [comment]
Of course!
