### ISSUE TITLE
Steam games

### ISSUE THREAD

**Issue by hmlendea** [bilelmoussaoui/StartupWMClassFixer#26]
I have a personal list of WMClasses for a bunch of Steam games.

Here: https://github.com/hmlendea/linux-setup-script/blob/master/data/steam-wmclasses.txt

Are you interested in integrating those apps in your list? If yes, I can help with that.

Note: There are 2-3 games there that use the WMClass from the Windows (Proton) version of the game instead of the native one because either the game is broken/outdated on Linux or achievements don't work on Linux.

**Comment by bilelmoussaoui** [comment]
feel free to send a merge request

**Comment by hmlendea** [comment]
Created a PR: #27

**Comment by bilelmoussaoui** [comment]
Feel free to send a PR for future apps
